theme:
  name: material
  palette:
    scheme: dirac
  features:
    - tabs
  logo: assets/dirac_logo.png
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.expand
    - navigation.top

extra_css:
    - stylesheets/dirac.css

site_name: DiRAC Extreme Scaling User Documentation
repo_url: https://github.com/EPCCed/dirac-docs.git
repo_name: EPCCed/dirac-docs
edit_uri: edit/main/docs/

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - "Documentation overview": index.md
  - "Hardware": hardware.md
  - "Connecting to Tursa": connecting.md
  - "Data management and transfer": data.md
  - "Software environment": sw-environment.md
  - "Running jobs on Tursa": 
    - "Current scheduler setup": scheduler.md
    - "Updated scheduler setup: Jul 2026": scheduler-update-2026.md
  - "Spack on Tursa": spack.md
  - "Profiling": profiling.md

