theme:
  name: material
  palette:
    scheme: default
  features:
    - tabs
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.expand
    - navigation.top
  
site_name: DiRAC Extreme Scaling User Documentation
repo_url: https://github.com/EPCCed/dirac-docs.git
repo_name: EPCCed/dirac-docs
edit_uri: edit/main/docs/

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - "Documentation overview": index.md
  - "Tursa User Guide":
    - "Overview": tursa-user-guide/index.md
    - "Hardware": tursa-user-guide/hardware.md
    - "Connecting to Tursa": tursa-user-guide/connecting.md
    - "Data Management and transfer": tursa-user-guide/data.md
    - "Software environment": tursa-user-guide/sw-environment.md
    - "Running jobs on Tursa": tursa-user-guide/scheduler.md

